package com.example.demo.entity;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.personUuid
     *
     * @mbggenerated
     */
    private String personuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.uuid
     *
     * @return the value of tb_account.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.uuid
     *
     * @param uuid the value for tb_account.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.personUuid
     *
     * @return the value of tb_account.personUuid
     *
     * @mbggenerated
     */
    public String getPersonuuid() {
        return personuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.personUuid
     *
     * @param personuuid the value for tb_account.personUuid
     *
     * @mbggenerated
     */
    public void setPersonuuid(String personuuid) {
        this.personuuid = personuuid == null ? null : personuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.account
     *
     * @return the value of tb_account.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.account
     *
     * @param account the value for tb_account.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.password
     *
     * @return the value of tb_account.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.password
     *
     * @param password the value for tb_account.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}