package com.example.demo.entity;

public class Lesson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lesson.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lesson.lessonId
     *
     * @mbggenerated
     */
    private String lessonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lesson.lessonName
     *
     * @mbggenerated
     */
    private String lessonname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lesson.lessonType
     *
     * @mbggenerated
     */
    private String lessontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lesson.startTime
     *
     * @mbggenerated
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lesson.endTime
     *
     * @mbggenerated
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lesson.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lesson.uuid
     *
     * @return the value of tb_lesson.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lesson.uuid
     *
     * @param uuid the value for tb_lesson.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lesson.lessonId
     *
     * @return the value of tb_lesson.lessonId
     *
     * @mbggenerated
     */
    public String getLessonid() {
        return lessonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lesson.lessonId
     *
     * @param lessonid the value for tb_lesson.lessonId
     *
     * @mbggenerated
     */
    public void setLessonid(String lessonid) {
        this.lessonid = lessonid == null ? null : lessonid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lesson.lessonName
     *
     * @return the value of tb_lesson.lessonName
     *
     * @mbggenerated
     */
    public String getLessonname() {
        return lessonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lesson.lessonName
     *
     * @param lessonname the value for tb_lesson.lessonName
     *
     * @mbggenerated
     */
    public void setLessonname(String lessonname) {
        this.lessonname = lessonname == null ? null : lessonname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lesson.lessonType
     *
     * @return the value of tb_lesson.lessonType
     *
     * @mbggenerated
     */
    public String getLessontype() {
        return lessontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lesson.lessonType
     *
     * @param lessontype the value for tb_lesson.lessonType
     *
     * @mbggenerated
     */
    public void setLessontype(String lessontype) {
        this.lessontype = lessontype == null ? null : lessontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lesson.startTime
     *
     * @return the value of tb_lesson.startTime
     *
     * @mbggenerated
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lesson.startTime
     *
     * @param starttime the value for tb_lesson.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lesson.endTime
     *
     * @return the value of tb_lesson.endTime
     *
     * @mbggenerated
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lesson.endTime
     *
     * @param endtime the value for tb_lesson.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lesson.status
     *
     * @return the value of tb_lesson.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lesson.status
     *
     * @param status the value for tb_lesson.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}