package com.example.demo.entity;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderId
     *
     * @mbggenerated
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.sponsorUuid
     *
     * @mbggenerated
     */
    private String sponsoruuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.sponsorName
     *
     * @mbggenerated
     */
    private String sponsorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.assigneeUuid
     *
     * @mbggenerated
     */
    private String assigneeuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.assigneeName
     *
     * @mbggenerated
     */
    private String assigneename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.beneficiaryUuid
     *
     * @mbggenerated
     */
    private String beneficiaryuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.beneficiaryName
     *
     * @mbggenerated
     */
    private String beneficiaryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.lastModifyTime
     *
     * @mbggenerated
     */
    private Date lastmodifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.uuid
     *
     * @return the value of tb_order.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.uuid
     *
     * @param uuid the value for tb_order.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderId
     *
     * @return the value of tb_order.orderId
     *
     * @mbggenerated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderId
     *
     * @param orderid the value for tb_order.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.sponsorUuid
     *
     * @return the value of tb_order.sponsorUuid
     *
     * @mbggenerated
     */
    public String getSponsoruuid() {
        return sponsoruuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.sponsorUuid
     *
     * @param sponsoruuid the value for tb_order.sponsorUuid
     *
     * @mbggenerated
     */
    public void setSponsoruuid(String sponsoruuid) {
        this.sponsoruuid = sponsoruuid == null ? null : sponsoruuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.sponsorName
     *
     * @return the value of tb_order.sponsorName
     *
     * @mbggenerated
     */
    public String getSponsorname() {
        return sponsorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.sponsorName
     *
     * @param sponsorname the value for tb_order.sponsorName
     *
     * @mbggenerated
     */
    public void setSponsorname(String sponsorname) {
        this.sponsorname = sponsorname == null ? null : sponsorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.assigneeUuid
     *
     * @return the value of tb_order.assigneeUuid
     *
     * @mbggenerated
     */
    public String getAssigneeuuid() {
        return assigneeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.assigneeUuid
     *
     * @param assigneeuuid the value for tb_order.assigneeUuid
     *
     * @mbggenerated
     */
    public void setAssigneeuuid(String assigneeuuid) {
        this.assigneeuuid = assigneeuuid == null ? null : assigneeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.assigneeName
     *
     * @return the value of tb_order.assigneeName
     *
     * @mbggenerated
     */
    public String getAssigneename() {
        return assigneename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.assigneeName
     *
     * @param assigneename the value for tb_order.assigneeName
     *
     * @mbggenerated
     */
    public void setAssigneename(String assigneename) {
        this.assigneename = assigneename == null ? null : assigneename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.beneficiaryUuid
     *
     * @return the value of tb_order.beneficiaryUuid
     *
     * @mbggenerated
     */
    public String getBeneficiaryuuid() {
        return beneficiaryuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.beneficiaryUuid
     *
     * @param beneficiaryuuid the value for tb_order.beneficiaryUuid
     *
     * @mbggenerated
     */
    public void setBeneficiaryuuid(String beneficiaryuuid) {
        this.beneficiaryuuid = beneficiaryuuid == null ? null : beneficiaryuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.beneficiaryName
     *
     * @return the value of tb_order.beneficiaryName
     *
     * @mbggenerated
     */
    public String getBeneficiaryname() {
        return beneficiaryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.beneficiaryName
     *
     * @param beneficiaryname the value for tb_order.beneficiaryName
     *
     * @mbggenerated
     */
    public void setBeneficiaryname(String beneficiaryname) {
        this.beneficiaryname = beneficiaryname == null ? null : beneficiaryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.amount
     *
     * @return the value of tb_order.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.amount
     *
     * @param amount the value for tb_order.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.createTime
     *
     * @return the value of tb_order.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.createTime
     *
     * @param createtime the value for tb_order.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.lastModifyTime
     *
     * @return the value of tb_order.lastModifyTime
     *
     * @mbggenerated
     */
    public Date getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.lastModifyTime
     *
     * @param lastmodifytime the value for tb_order.lastModifyTime
     *
     * @mbggenerated
     */
    public void setLastmodifytime(Date lastmodifytime) {
        this.lastmodifytime = lastmodifytime;
    }
}