package com.example.demo.entity;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.personName
     *
     * @mbggenerated
     */
    private String personname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.birthday
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.role
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.insertTime
     *
     * @mbggenerated
     */
    private String inserttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person.lastModifyTime
     *
     * @mbggenerated
     */
    private String lastmodifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.uuid
     *
     * @return the value of tb_person.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.uuid
     *
     * @param uuid the value for tb_person.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.personName
     *
     * @return the value of tb_person.personName
     *
     * @mbggenerated
     */
    public String getPersonname() {
        return personname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.personName
     *
     * @param personname the value for tb_person.personName
     *
     * @mbggenerated
     */
    public void setPersonname(String personname) {
        this.personname = personname == null ? null : personname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.gender
     *
     * @return the value of tb_person.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.gender
     *
     * @param gender the value for tb_person.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.birthday
     *
     * @return the value of tb_person.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.birthday
     *
     * @param birthday the value for tb_person.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.role
     *
     * @return the value of tb_person.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.role
     *
     * @param role the value for tb_person.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.nation
     *
     * @return the value of tb_person.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.nation
     *
     * @param nation the value for tb_person.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.province
     *
     * @return the value of tb_person.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.province
     *
     * @param province the value for tb_person.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.city
     *
     * @return the value of tb_person.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.city
     *
     * @param city the value for tb_person.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.phone
     *
     * @return the value of tb_person.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.phone
     *
     * @param phone the value for tb_person.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.insertTime
     *
     * @return the value of tb_person.insertTime
     *
     * @mbggenerated
     */
    public String getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.insertTime
     *
     * @param inserttime the value for tb_person.insertTime
     *
     * @mbggenerated
     */
    public void setInserttime(String inserttime) {
        this.inserttime = inserttime == null ? null : inserttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person.lastModifyTime
     *
     * @return the value of tb_person.lastModifyTime
     *
     * @mbggenerated
     */
    public String getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person.lastModifyTime
     *
     * @param lastmodifytime the value for tb_person.lastModifyTime
     *
     * @mbggenerated
     */
    public void setLastmodifytime(String lastmodifytime) {
        this.lastmodifytime = lastmodifytime == null ? null : lastmodifytime.trim();
    }
}