package com.example.demo.entity;

public class Schedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule.scheduleId
     *
     * @mbggenerated
     */
    private String scheduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule.lessonUuid
     *
     * @mbggenerated
     */
    private String lessonuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule.lessonType
     *
     * @mbggenerated
     */
    private String lessontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule.startTime
     *
     * @mbggenerated
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule.endTime
     *
     * @mbggenerated
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule.teacherUuid
     *
     * @mbggenerated
     */
    private String teacheruuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule.status
     *
     * @mbggenerated
     */
    private String status;

    public Lesson getLesson() {
        return lesson;
    }

    public void setLesson(Lesson lesson) {
        this.lesson = lesson;
    }

    private Lesson lesson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule.uuid
     *
     * @return the value of tb_schedule.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule.uuid
     *
     * @param uuid the value for tb_schedule.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule.scheduleId
     *
     * @return the value of tb_schedule.scheduleId
     *
     * @mbggenerated
     */
    public String getScheduleid() {
        return scheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule.scheduleId
     *
     * @param scheduleid the value for tb_schedule.scheduleId
     *
     * @mbggenerated
     */
    public void setScheduleid(String scheduleid) {
        this.scheduleid = scheduleid == null ? null : scheduleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule.lessonUuid
     *
     * @return the value of tb_schedule.lessonUuid
     *
     * @mbggenerated
     */
    public String getLessonuuid() {
        return lessonuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule.lessonUuid
     *
     * @param lessonuuid the value for tb_schedule.lessonUuid
     *
     * @mbggenerated
     */
    public void setLessonuuid(String lessonuuid) {
        this.lessonuuid = lessonuuid == null ? null : lessonuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule.lessonType
     *
     * @return the value of tb_schedule.lessonType
     *
     * @mbggenerated
     */
    public String getLessontype() {
        return lessontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule.lessonType
     *
     * @param lessontype the value for tb_schedule.lessonType
     *
     * @mbggenerated
     */
    public void setLessontype(String lessontype) {
        this.lessontype = lessontype == null ? null : lessontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule.startTime
     *
     * @return the value of tb_schedule.startTime
     *
     * @mbggenerated
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule.startTime
     *
     * @param starttime the value for tb_schedule.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule.endTime
     *
     * @return the value of tb_schedule.endTime
     *
     * @mbggenerated
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule.endTime
     *
     * @param endtime the value for tb_schedule.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule.teacherUuid
     *
     * @return the value of tb_schedule.teacherUuid
     *
     * @mbggenerated
     */
    public String getTeacheruuid() {
        return teacheruuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule.teacherUuid
     *
     * @param teacheruuid the value for tb_schedule.teacherUuid
     *
     * @mbggenerated
     */
    public void setTeacheruuid(String teacheruuid) {
        this.teacheruuid = teacheruuid == null ? null : teacheruuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule.status
     *
     * @return the value of tb_schedule.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule.status
     *
     * @param status the value for tb_schedule.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}