package com.example.demo.entity;

public class ScheduleStudentRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule_student_rel.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule_student_rel.scheduleId
     *
     * @mbggenerated
     */
    private String scheduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_schedule_student_rel.studentId
     *
     * @mbggenerated
     */
    private String studentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule_student_rel.uuid
     *
     * @return the value of tb_schedule_student_rel.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule_student_rel.uuid
     *
     * @param uuid the value for tb_schedule_student_rel.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule_student_rel.scheduleId
     *
     * @return the value of tb_schedule_student_rel.scheduleId
     *
     * @mbggenerated
     */
    public String getScheduleid() {
        return scheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule_student_rel.scheduleId
     *
     * @param scheduleid the value for tb_schedule_student_rel.scheduleId
     *
     * @mbggenerated
     */
    public void setScheduleid(String scheduleid) {
        this.scheduleid = scheduleid == null ? null : scheduleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_schedule_student_rel.studentId
     *
     * @return the value of tb_schedule_student_rel.studentId
     *
     * @mbggenerated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_schedule_student_rel.studentId
     *
     * @param studentid the value for tb_schedule_student_rel.studentId
     *
     * @mbggenerated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }
}