package com.example.demo.entity;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.studentId
     *
     * @mbggenerated
     */
    private String studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.personUuid
     *
     * @mbggenerated
     */
    private String personuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.admissionTime
     *
     * @mbggenerated
     */
    private String admissiontime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.momPhone
     *
     * @mbggenerated
     */
    private String momphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.dadPhone
     *
     * @mbggenerated
     */
    private String dadphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.status
     *
     * @mbggenerated
     */
    private String status;

    private Person person;

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.uuid
     *
     * @return the value of tb_student.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.uuid
     *
     * @param uuid the value for tb_student.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.studentId
     *
     * @return the value of tb_student.studentId
     *
     * @mbggenerated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.studentId
     *
     * @param studentid the value for tb_student.studentId
     *
     * @mbggenerated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.personUuid
     *
     * @return the value of tb_student.personUuid
     *
     * @mbggenerated
     */
    public String getPersonuuid() {
        return personuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.personUuid
     *
     * @param personuuid the value for tb_student.personUuid
     *
     * @mbggenerated
     */
    public void setPersonuuid(String personuuid) {
        this.personuuid = personuuid == null ? null : personuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.level
     *
     * @return the value of tb_student.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.level
     *
     * @param level the value for tb_student.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.admissionTime
     *
     * @return the value of tb_student.admissionTime
     *
     * @mbggenerated
     */
    public String getAdmissiontime() {
        return admissiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.admissionTime
     *
     * @param admissiontime the value for tb_student.admissionTime
     *
     * @mbggenerated
     */
    public void setAdmissiontime(String admissiontime) {
        this.admissiontime = admissiontime == null ? null : admissiontime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.momPhone
     *
     * @return the value of tb_student.momPhone
     *
     * @mbggenerated
     */
    public String getMomphone() {
        return momphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.momPhone
     *
     * @param momphone the value for tb_student.momPhone
     *
     * @mbggenerated
     */
    public void setMomphone(String momphone) {
        this.momphone = momphone == null ? null : momphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.dadPhone
     *
     * @return the value of tb_student.dadPhone
     *
     * @mbggenerated
     */
    public String getDadphone() {
        return dadphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.dadPhone
     *
     * @param dadphone the value for tb_student.dadPhone
     *
     * @mbggenerated
     */
    public void setDadphone(String dadphone) {
        this.dadphone = dadphone == null ? null : dadphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.status
     *
     * @return the value of tb_student.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.status
     *
     * @param status the value for tb_student.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}