package com.example.demo.entity;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacherId
     *
     * @mbggenerated
     */
    private String teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.personUuid
     *
     * @mbggenerated
     */
    private String personuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.entryTime
     *
     * @mbggenerated
     */
    private String entrytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.status
     *
     * @mbggenerated
     */
    private String status;

    private Person person;

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.uuid
     *
     * @return the value of tb_teacher.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.uuid
     *
     * @param uuid the value for tb_teacher.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacherId
     *
     * @return the value of tb_teacher.teacherId
     *
     * @mbggenerated
     */
    public String getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacherId
     *
     * @param teacherid the value for tb_teacher.teacherId
     *
     * @mbggenerated
     */
    public void setTeacherid(String teacherid) {
        this.teacherid = teacherid == null ? null : teacherid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.personUuid
     *
     * @return the value of tb_teacher.personUuid
     *
     * @mbggenerated
     */
    public String getPersonuuid() {
        return personuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.personUuid
     *
     * @param personuuid the value for tb_teacher.personUuid
     *
     * @mbggenerated
     */
    public void setPersonuuid(String personuuid) {
        this.personuuid = personuuid == null ? null : personuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.level
     *
     * @return the value of tb_teacher.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.level
     *
     * @param level the value for tb_teacher.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.entryTime
     *
     * @return the value of tb_teacher.entryTime
     *
     * @mbggenerated
     */
    public String getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.entryTime
     *
     * @param entrytime the value for tb_teacher.entryTime
     *
     * @mbggenerated
     */
    public void setEntrytime(String entrytime) {
        this.entrytime = entrytime == null ? null : entrytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.status
     *
     * @return the value of tb_teacher.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.status
     *
     * @param status the value for tb_teacher.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}