package com.example.demo.dao;

import com.example.demo.entity.AllRelations;

public interface AllRelationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_room_teacher_lesson_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_room_teacher_lesson_rel
     *
     * @mbggenerated
     */
    int insert(AllRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_room_teacher_lesson_rel
     *
     * @mbggenerated
     */
    int insertSelective(AllRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_room_teacher_lesson_rel
     *
     * @mbggenerated
     */
    AllRelations selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_room_teacher_lesson_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AllRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_room_teacher_lesson_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AllRelations record);
}