package com.example.demo.dao;

import com.example.demo.entity.FixOrder;

import java.util.List;

public interface FixOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fix_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fix_order
     *
     * @mbggenerated
     */
    int insert(FixOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fix_order
     *
     * @mbggenerated
     */
    int insertSelective(FixOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fix_order
     *
     * @mbggenerated
     */
    FixOrder selectByPrimaryKey(String uuid);

    List<FixOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fix_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FixOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fix_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FixOrder record);
}