package com.example.demo.dao;

import com.example.demo.entity.Lesson;

import java.util.List;

public interface LessonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lesson
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lesson
     *
     * @mbggenerated
     */
    int insert(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lesson
     *
     * @mbggenerated
     */
    int insertSelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lesson
     *
     * @mbggenerated
     */
    Lesson selectByPrimaryKey(String uuid);

    List<Lesson> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Lesson record);
}