package com.example.demo.dao;

import com.example.demo.entity.ScheduleStudentRel;

public interface ScheduleStudentRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_student_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_student_rel
     *
     * @mbggenerated
     */
    int insert(ScheduleStudentRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_student_rel
     *
     * @mbggenerated
     */
    int insertSelective(ScheduleStudentRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_student_rel
     *
     * @mbggenerated
     */
    ScheduleStudentRel selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_student_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScheduleStudentRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule_student_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScheduleStudentRel record);
}