package com.example.demo.dao;

import com.example.demo.entity.Schedule;

import java.util.List;

public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule
     *
     * @mbggenerated
     */
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule
     *
     * @mbggenerated
     */
    int insertSelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule
     *
     * @mbggenerated
     */
    Schedule selectByPrimaryKey(String uuid);

    List<Schedule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Schedule record);
}